apiVersion: v2
appVersion: "4.4.4"
description: Unleash is a open source feature flag & toggle system, that gives you a great overview over all feature toggles across all your applications and services.
maintainers:
- name: evanstucker-hates-2fa
- name: ivarconr
  email: ivarconr@gmail.com
name: unleash
sources:
  - https://github.com/Unleash/unleash
  - https://github.com/Unleash/unleash-docker
  - https://github.com/Unleash/helm-charts
type: application
version: 2.6.1
